-- DROP SCHEMA public;

CREATE SCHEMA public AUTHORIZATION pg_database_owner;

COMMENT ON SCHEMA public IS 'standard public schema';

-- DROP SEQUENCE public.activity_act_id_seq;

CREATE SEQUENCE public.activity_act_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.complaint_comp_id_seq;

CREATE SEQUENCE public.complaint_comp_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.customer_profiles_profile_id_seq;

CREATE SEQUENCE public.customer_profiles_profile_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.products_product_id_seq;

CREATE SEQUENCE public.products_product_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.recommendations_rec_id_seq;

CREATE SEQUENCE public.recommendations_rec_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.transactions_trx_id_seq;

CREATE SEQUENCE public.transactions_trx_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;-- public.activity definition

-- Drop table

-- DROP TABLE public.activity;

CREATE TABLE public.activity (
	act_id serial4 NOT NULL,
	nama_activity text NOT NULL,
	avg_data_usage_gb float8 DEFAULT 1.0 NULL,
	call_min float8 DEFAULT 0.0 NULL,
	call_max float8 DEFAULT 0.0 NULL,
	video_min float8 DEFAULT 0.0 NULL,
	video_max float8 DEFAULT 0.0 NULL,
	CONSTRAINT activity_pkey PRIMARY KEY (act_id)
);


-- public.products definition

-- Drop table

-- DROP TABLE public.products;

CREATE TABLE public.products (
	product_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	category text NOT NULL,
	"name" text NOT NULL,
	price numeric(10, 2) NOT NULL,
	data_quota_internet int4 DEFAULT 0 NULL,
	data_quota text NULL,
	validity int4 DEFAULT 0 NULL,
	description text NULL,
	is_active bool DEFAULT true NULL,
	CONSTRAINT products_pkey PRIMARY KEY (product_id)
);


-- public.users definition

-- Drop table

-- DROP TABLE public.users;

CREATE TABLE public.users (
	user_id uuid DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	email text NULL,
	phone_number text NULL,
	password_hash text NULL,
	created_at timestamptz DEFAULT now() NULL,
	CONSTRAINT users_email_key UNIQUE (email),
	CONSTRAINT users_pkey PRIMARY KEY (user_id)
);


-- public.complaint definition

-- Drop table

-- DROP TABLE public.complaint;

CREATE TABLE public.complaint (
	comp_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_id uuid NULL,
	phone_number text NULL,
	kategori_masalah text NULL,
	judul_laporan text NULL,
	detail_kendala text NULL,
	tanggal timestamptz DEFAULT now() NULL,
	CONSTRAINT complaint_pkey PRIMARY KEY (comp_id),
	CONSTRAINT complaint_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE
);


-- public.customer_profiles definition

-- Drop table

-- DROP TABLE public.customer_profiles;

CREATE TABLE public.customer_profiles (
	profile_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_id uuid NULL,
	act_id int4 NULL,
	plan_type text NULL,
	device_brand text NULL,
	monthly_spend numeric(10, 2) NULL,
	avg_data_usage_gb float8 NULL,
	pct_video_usage float8 NULL,
	avg_call_duration float8 NULL,
	topup_freq int4 NULL,
	travel_score float8 NULL,
	complaint_count int4 DEFAULT 0 NULL,
	last_updated timestamptz DEFAULT now() NULL,
	CONSTRAINT customer_profiles_pkey PRIMARY KEY (profile_id),
	CONSTRAINT customer_profiles_act_id_fkey FOREIGN KEY (act_id) REFERENCES public.activity(act_id) ON DELETE SET NULL,
	CONSTRAINT customer_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE
);


-- public.recommendations definition

-- Drop table

-- DROP TABLE public.recommendations;

CREATE TABLE public.recommendations (
	rec_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_id uuid NULL,
	target_offer text NULL,
	confidence_score float8 NULL,
	reasoning text NULL,
	generated_at timestamptz DEFAULT now() NULL,
	CONSTRAINT recommendations_pkey PRIMARY KEY (rec_id),
	CONSTRAINT recommendations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE
);


-- public.transactions definition

-- Drop table

-- DROP TABLE public.transactions;

CREATE TABLE public.transactions (
	trx_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_id uuid NULL,
	product_id int8 NULL,
	amount numeric(10, 2) NOT NULL,
	purchase_date timestamptz DEFAULT now() NULL,
	status text DEFAULT 'SUCCESS'::text NULL,
	CONSTRAINT transactions_pkey PRIMARY KEY (trx_id),
	CONSTRAINT transactions_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(product_id) ON DELETE SET NULL,
	CONSTRAINT transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE
);